
server:
  port: 8080
    
logging.level:
  web: INFO
  root: INFO
  '[com.bptn]': DEBUG
  '[org.hibernate]': INFO
  '[org.hibernate.cfg.annotations.EntityBinder]': DEBUG
  '[org.springframework.beans.factory.support.DefaultListableBeanFactory]': DEBUG
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feed_application 
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        '[format_sql]': true
     
api:
  key: 8a5a26a87b114b2b81e939653c65abea
  base.url: https://newsapi.org/v2/everything